feedrate scaling mods
ORNLSlicer/Slicer-2 pull request #52
Opened 2024-07-10 15:18 UTC by omerbaa

2024-07-25 14:14 UTC, aroschli submitted a review, later dismissed

2024-07-26 12:20 UTC, liamnwhite1 requested changes
Changes look good and code appears to execute normally. I've made some minor formatting requests as well as some minor improvements. All these requests are in the form of suggestions with the correct code supplied so you should be able to simply accept and commit the suggestions. This review process is new for us so please let me know if you are not able to simply accept and commit the suggestions. Additionally, if you have any questions please let me know.

2024-07-26 12:20 UTC, liamnwhite1 commented on src/gcode/parsers/common_parser.cpp
> +                                m_lines.removeAt(cmdIndex);
```suggestion
                        int cmd_index = current_layer_motion_end->getLineNumber() - 1;
                        QString& line = m_lines[cmd_index];
                        
                        if(line.startsWith("M3 ")) {
                            QRegularExpressionMatch myMatch = m_s_param_and_value.match(line);
                            double value = myMatch.capturedRef().mid(1).toDouble();
                            
                            if(value != 0) {
                                double extruderModifier = sb->setting< double >(Constants::MaterialSettings::Cooling::kExtruderScaleFactor);
                                
                                // If slowing down, the multiplier for the extruder should be the inverse of the scale factor
                                if(modifier < 1) {
                                    extruderModifier = 1 / extruderModifier;
                                }
                                
                                line = line.leftRef(myMatch.capturedStart()) %
                                       m_s_parameter %
                                       QString::number(value * modifier * extruderModifier, 'f', 4) %
                                       line.midRef(myMatch.capturedEnd());
                                
                                m_lines.insert(cmd_index + 1, line);
                                m_lines.removeAt(cmd_index);
```

2024-07-26 12:20 UTC, liamnwhite1 commented on src/utilities/mathutils.cpp
> +                   QString::number(miliSeconds).leftJustified(3, '0');
```suggestion
            int milliseconds = round((sec - seconds) * 1000);
            return QString::number(hours) + ":" +
                   QString::number(minutes).rightJustified(2, '0') + ":" +
                   QString::number(remainingSeconds).rightJustified(2, '0') + "." +
                   QString::number(milliseconds).leftJustified(3, '0');
```

2024-07-26 12:20 UTC, liamnwhite1 commented on src/windows/layer_times_window.cpp
> +            if(i ==0) {
```suggestion
            if(i == 0) {
```

2024-07-26 12:20 UTC, liamnwhite1 commented on src/windows/layer_times_window.cpp
> +                currentTotal += adjustedTime;
```suggestion
                double adjusted_time = current_time() / m_layer_FR_modifiers[i];
                if(m_layer_FR_modifiers[i] != 1) {
                    oneLayer += " Adjusted " % MathUtils::formattedTimeSpanHHMMSS(adjusted_time) % ",";
                }
                currentTotal += adjusted_time;
```

2024-07-26 15:14 UTC, cadkin requested changes
The main issue I see is the usage of `double` versus `Time` objects. We use unit objects to automatically annotate the code though types; using `double` means we loose this information. Additionally, it also strips out the unit-safety and conversion functions that the unit objects provide.

Otherwise, things look good! Let me know if you have any questions related to making these changes.

2024-07-26 15:14 UTC, cadkin commented on include/windows/layer_times_window.h
> +            QList<double> m_layer_FR_modifiers;
This should likely be a vector of `Time` objects rather than raw doubles; check the other usages of double as well to make sure they are the appropriate type.

2024-07-26 15:14 UTC, cadkin commented on src/main.cpp
> +    qRegisterMetaType<QList<double>>("QList<double>");
Should not be needed if data type is switched to `Time`.

2024-07-31 19:47 UTC, mborish submitted a review, later dismissed

2024-07-31 20:33 UTC, omerbaa commented on src/main.cpp
> +    qRegisterMetaType<QList<double>>("QList<double>");
Does not apply

2024-07-31 20:35 UTC, omerbaa commented on include/windows/layer_times_window.h
> +            QList<double> m_layer_FR_modifiers;
Modifier is a computed constant multiplier, hence has no units, there assumption that it is time value is incorrect.
If that is not the case please feel free to modify as needed.

2024-08-01 13:12 UTC, liamnwhite1 approved these changes
Looks good! Thank you for making the changes!

2024-08-01 23:20 UTC, cadkin approved these changes
LGTM!

2024-08-02 13:38 UTC, merged