Image Generation Capability
ORNLSlicer/Slicer-2 pull request #55
Opened 2024-08-05 12:31 UTC by mborish

Necessary changes to generate binary images with specific characteristics instead of gcode.

2024-08-05 21:34 UTC, aroschli commented on src/managers/session_manager.cpp
> -            file_name = new_part->name();
These changes cause a crash when loading a project. Simply reverting back to the previous version for these lines of code resolves the issue.

How to test:
Open Slicer 2
Load an object, slice it, save project
Close Slicer 2
Load the previously loaded project
It will crash with the code in its current state, but reverting to the previous version should work.

2024-08-05 21:34 UTC, aroschli requested changes
Everything looks good and functions properly, just need to revert some of the changes to file_name in session_manager.cpp to prevent the project system from crashing.

2024-08-06 17:46 UTC, liamnwhite1 requested changes
Program crashing when loading a project needs to be addressed.

2024-08-06 17:46 UTC, liamnwhite1 commented on src/managers/session_manager.cpp
> -            file_name = new_part->name();
Confirmed that the program crashes when loading a project.

2024-08-07 15:22 UTC, aroschli approved these changes

2024-08-07 15:23 UTC, liamnwhite1 approved these changes

2024-08-09 16:41 UTC, merged