Use adjusted time for g-code output
ORNLSlicer/Slicer-2 pull request #56
Opened 2024-08-05 21:36 UTC by aroschli

2024-08-06 18:12 UTC, liamnwhite1 requested changes
Looks good. My only recommendation is to use std::numeric_limits<int> instead of the INT_MAX/MIN macros.

2024-08-06 18:12 UTC, liamnwhite1 commented on src/threading/gcode_loader.cpp
> +                adjusted_max_time = INT_MIN;
```suggestion
                min_time = std::numeric_limits<int>::max();
                max_time = std::numeric_limits<int>::min();
                adjusted_min_time = std::numeric_limits<int>::max();
                adjusted_max_time = std::numeric_limits<int>::min();
```

2024-08-07 15:30 UTC, liamnwhite1 approved these changes

2024-08-07 17:40 UTC, mborish approved these changes

2024-08-13 18:24 UTC, cadkin approved these changes
lgtm!

2024-08-13 20:35 UTC, merged